export const emisorasData = [
  {
    id: 1,
    image: require('../assets/emisorasPortadas/activaFm.webp'),
    background: require('../assets/backgrounds/back-activa-v2.jpg'),
    banner: require('../assets/bannersSearch/banner-activa.jpg'),
    title: 'Activa FM',
    description: 'LA MEJOR COMBINACIÓN DE ÉXITOS',
    color: '#e73b3c',
  },
  {
    id: 4,
    image: require('../assets/emisorasPortadas/bikini.webp'),
    background: require('../assets/backgrounds/back-bikini-v2.jpg'),
    banner: require('../assets/bannersSearch/banner-bikini.jpg'),
    title: 'Bikini FM',
    description: 'LA RADIO DEL REMEMBER',
    color: '#66ccff',
  },
  {
    id: 96,
    image: require('../assets/emisorasPortadas/comboi.webp'),
    background: require('../assets/backgrounds/back-comboi.jpg'),
    banner: require('../assets/bannersSearch/banner-comboi.jpg'),
    title: 'Comboi FM',
    description: 'LA RADIO DE LA TERRETA',
    color: '#ffffff',
  },
  {
    id: 76,
    image: require('../assets/emisorasPortadas/corazonFm.webp'),
    background: require('../assets/backgrounds/back-corazón.jpg'),
    banner: require('../assets/bannersSearch/banner-corazon.jpg'),
    title: 'Corazon FM',
    description: 'LA MÚSICA QUE TE ENAMORA',
    color: '#ffffff',
  },
  {
    id: 5,
    image: require('../assets/emisorasPortadas/esencia.webp'),
    background: require('../assets/backgrounds/back-esencia.jpg'),
    banner: require('../assets/bannersSearch/banner-esencia.jpg'),
    title: 'Esencia FM',
    description: 'LA ESENCIA DE NUESTRA MÚSICA',
    color: '#ff3366',
  },
  {
    id: 6,
    image: require('../assets/emisorasPortadas/goldFm.webp'),
    background: require('../assets/backgrounds/back-gold.jpg'),
    banner: require('../assets/bannersSearch/banner-gold.jpg'),
    title: 'Gold FM',
    description: 'LA MÚSICA DE TU VIDA',
    color: '#ffffff',
  },
  {
    id: 8,
    image: require('../assets/emisorasPortadas/laFlamenca.webp'),
    background: require('../assets/backgrounds/back-flamenca.jpg'),
    banner: require('../assets/bannersSearch/banner-flamenca.jpg'),
    title: 'La Flamenca',
    description: '¡FLAMENCO Y OLÉ!',
    color: '#33cc33',
  },
  {
    id: 14,
    image: require('../assets/emisorasPortadas/laIndie.webp'),
    background: require('../assets/backgrounds/back-indie.jpg'),
    banner: require('../assets/bannersSearch/banner-indie.jpg'),
    title: 'La Indie',
    description: 'LA EMISORA QUE POCOS ENTIENDEN',
    color: '#403437',
  },
  {
    id: 3,
    image: require('../assets/emisorasPortadas/laMega.webp'),
    background: require('../assets/backgrounds/back-mega.jpg'),
    banner: require('../assets/bannersSearch/banner-mega.jpg'),
    title: 'La Mega',
    description: '¡SÓLO BAILAMOS!',
    color: '#9900cc',
  },
  {
    id: 9,
    image: require('../assets/emisorasPortadas/laQueSuena.webp'),
    background: require('../assets/backgrounds/back-laquesuena.jpg'),
    banner: require('../assets/bannersSearch/banner-laquesuena.jpg'),
    title: 'La Que Suena',
    description: '¡PARA QUE NO PARES!',
    color: '#afc435',
  },
  {
    id: 12,
    image: require('../assets/emisorasPortadas/masActiva.webp'),
    background: require('../assets/backgrounds/back-+activa.jpg'),
    banner: require('../assets/bannersSearch/banner-+activa.jpg'),
    title: '+Activa',
    description: 'LA MEJOR COMBINACIÓN DE ÉXITOS DE AYER Y HOY',
    color: '#e73b3c',
  },
  {
    id: 2,
    image: require('../assets/emisorasPortadas/muyBuena.webp'),
    background: require('../assets/backgrounds/back-muybuena.jpg'),
    banner: require('../assets/bannersSearch/banner-muybuena.jpg'),
    title: 'Muy Buena',
    description: '¡QUÉ BIEN SUENA!',
    color: '#ffcb03',
  },
  {
    id: 86,
    image: require('../assets/emisorasPortadas/radioHallo.webp'),
    background: require('../assets/backgrounds/back-hallo.jpg'),
    banner: require('../assets/bannersSearch/banner-hallo.jpg'),
    title: 'Radio Hallo',
    description: 'MUSIK, NACHRICHTEN UND VIELES MEHR',
    color: '#ffffff',
  },
  {
    id: 7,
    image: require('../assets/emisorasPortadas/rockstar.webp'),
    background: require('../assets/backgrounds/back-rockstar.jpg'),
    banner: require('../assets/bannersSearch/banner-rockstar.jpg'),
    title: 'Rockstar',
    description: 'LA RADIO DE LAS ESTRELLAS DE ROCK',
    color: '#cccccc',
  },
  {
    id: 95,
    image: require('../assets/emisorasPortadas/solLatino.webp'),
    background: require('../assets/backgrounds/back-latino.jpg'),
    banner: require('../assets/bannersSearch/banner-sollatino.jpg'),
    title: 'Sol Latino',
    description: 'NÚMERO 1 EN SALSA, MERENGUE Y MÁS',
    color: '#fecc03',
  },
];
